var list_palabras = ["alicates", "inefable",
    "cajonera", "analfabeto", "inadmisible", "cinturon",
    "nuez", "agarrochar", "agarrotar", "agarrotear", "agasajar", "agatizarse",
    "agaucharse", "agavillar", "agazapar", "agenciar", "agermanarse", "agigantar",
    "agilitar", "agilizar", "agitanar", "agitar", "aglomerar", "aglutinar", "agobiar",
    "agolar", "agolpar", "agonizar", "agorar", "agorgojarse", "agostar", "agotar", "agraciar",
    "agradar", "agradecer", "agramar", "agramilar", "agrandar", "agravar", "explanar", "explayar",
    "explicar", "explicitar", "explorar", "explosionar", "explotar", "expoliar", "exponer",
    "exportar", "expresar", "descolocar", "descolonizacion", "descolonizar", "descoloramiento",
    "descolorar", "descolorido", "descolorimiento", "descolorar", "descombrar", "descombro",
    "descomedidamente", "descomedido", "descomedimiento", "descomedirse", "descomer",
    "involuntariamente", "involuntariedad", "involuntario", "involutivo", "invulnerabilidad",
    "invulnerable", "invalidamente", "invalido", "inyeccion", "inyectable", "inyectar", "inyector",
    "inyungir", "inanime", "inedito", "inutil", "inutilmente", "ion", "ionizacion", "ionizar",
    "ionosfera", "idiota", "iotizacion", "ipecacuana", "iperita", "ipil", "perca",
    "percador", "percal", "percalina", "percance", "percanzar", "percatacion", "percatar",
    "percebe", "percebimiento", "percepcion", "perceptibilidad", "perceptible", "perceptiblemente",
    "perceptivo", "perceptor", "percha", "perchado", "perchar", "perchel", "perchelero",
    "perchero", "percheron", "perchonar", "perchon", "percibir", "percibo", "perclorato", "especiazion",
    "hidrolisis", "oximoron", "botellon"
];